import {
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleSlashed,
  Expand,
  Info,
  Instagram,
  ImageOff,
  Laptop,
  LayoutGrid,
  LayoutList,
  LucideProps,
  Menu,
  Moon,
  Paintbrush2,
  Palette,
  Pipette,
  SlidersHorizontal,
  SunMedium,
  Twitter,
  type Icon as LucideIcon,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  twitter: Twitter,
  instagram: Instagram,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  slidersHorizontal: SlidersHorizontal,
  info: Info,
  imageOff: ImageOff,
  menu: Menu,
  layoutGrid: LayoutGrid,
  layoutList: LayoutList,
  expand: Expand,
  palette: Palette,
  pipette: Pipette,
  paintbrush2: Paintbrush2,
  circleSlashed: CircleSlashed,
};
